import { INITIAL_MESSAGE } from "../lib/constants";
import { Message } from "../type/types";
import markdownToHtmlFormat from "./markdownToHtmlFormat";

export function htmlContent(chatHistory: Message[]) {
	return `
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<style>
			@page {
				margin: 25mm 20mm;
				size: A4;
				@bottom-right {
					content: "Page " counter(page) " of " counter(pages);
					font-family: 'Segoe UI', sans-serif;
					font-size: 10px;
					color: #6c757d;
				}
			}
			body {
				font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', sans-serif;
				line-height: 1.6;
				color: #2c3e50;
				margin: 0;
				padding: 0;
				background-color: #ffffff;
				font-size: 14px;
			}
			.header {
				text-align: center;
				margin-bottom: 40px;
				padding: 40px 30px;
				background-color: #f8f9fa;
				border: 2px solid #e9ecef;
				border-radius: 8px;
			}
			.logo-container {
				text-align: center;
				margin-bottom: 25px;
			}
			.logo {
				max-width: 180px;
				height: auto;
			}
			.header h1 {
				margin: 20px 0 10px;
				font-size: 28px;
				font-weight: 600;
				color: #2c3e50;
				letter-spacing: -0.5px;
			}
			.header p {
				margin: 0;
				font-size: 14px;
				color: #6c757d;
				font-weight: 400;
			}
			.conversation {
				max-width: 750px;
				margin: 0 auto;
			}
			.message {
				margin-bottom: 25px;
				page-break-inside: avoid;
				display: block;
			}
			.message.user {
				margin-left: 0;
			}
			.message.osca {
				margin-right: 0;
			}
			.sender-label {
				font-size: 12px;
				font-weight: 600;
				margin-bottom: 8px;
				text-transform: uppercase;
				letter-spacing: 1px;
				color: #495057;
			}
			.message.user .sender-label {
				text-align: left;
				color: #0d6efd;
			}
			.message.osca .sender-label {
				color: #198754;
			}
			.message-bubble {
				padding: 20px 24px;
				border-radius: 12px;
				position: relative;
				border: 1px solid #dee2e6;
				background-color: #ffffff;
				box-shadow: 0 2px 8px rgba(0,0,0,0.06);
			}
			.message.user .message-bubble {
				background-color: #f8f9ff;
				border-color: #d6d9ff;
				border-left: 4px solid #0d6efd;
			}
			.message.osca .message-bubble {
				background-color: #f8fff9;
				border-color: #d1f2d9;
				border-left: 4px solid #198754;
			}
			.message-text {
				font-size: 14px;
				line-height: 1.7;
				color: #2c3e50;
				margin: 0;
			}
			.message-text strong {
				font-weight: 600;
				color: #1a1a1a;
			}
			.message-text em {
				font-style: italic;
				color: #495057;
			}
			.message-text p {
				margin: 0 0 12px 0;
			}
			.message-text p:last-child {
				margin-bottom: 0;
			}
			.separator {
				height: 1px;
				background-color: #e9ecef;
				margin: 30px 0;
				border: none;
			}
			.footer {
				margin-top: 50px;
				padding-top: 20px;
				border-top: 1px solid #e9ecef;
				text-align: center;
				font-size: 12px;
				color: #6c757d;
			}
			@media print {
				body {
					-webkit-print-color-adjust: exact;
					print-color-adjust: exact;
				}
				.header {
					background-color: #f8f9fa !important;
					border-color: #e9ecef !important;
				}
				.message.user .message-bubble {
					background-color: #f8f9ff !important;
					border-color: #d6d9ff !important;
					border-left-color: #0d6efd !important;
				}
				.message.osca .message-bubble {
					background-color: #f8fff9 !important;
					border-color: #d1f2d9 !important;
					border-left-color: #198754 !important;
				}
			}
		</style>
	</head>
	<body>
		<div class="header">
			<div class="logo-container">
				<img src="https://www.onepointltd.com/wp-content/uploads/2020/06/logo-one-point.png" alt="OnePoint Logo" class="logo">
			</div>
			<h1>OSCA Chat Conversation</h1>
			<p>Generated on
			${new Date().toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric',
		hour: '2-digit',
		minute: '2-digit',
	})}
			</p>
		</div>
		<div class="conversation">
			${chatHistory
			.filter(message => !message.text.includes(INITIAL_MESSAGE))
			.map((message, index) => `
				<div class="message ${message.type}">
					<div class="sender-label">${message.type === 'user' ? 'User Query' : 'OSCA Response'}</div>
					<div class="message-bubble">
						<div class="message-text">${markdownToHtmlFormat(message.text)}</div>
					</div>
				</div>
				${index < chatHistory.length - 1 ? '<hr class="separator">' : ''}
			`).join('')}
		</div>
		<div class="footer">
			<p>This conversation was generated by OSCA (Onepoint Smart Company Advisor)</p>
			<p>© ${new Date().getFullYear()} OnePoint Ltd. All rights reserved.</p>
		</div>
	</body>
</html>
`;
}